version: '3'
services:
  server1:
    image: server
    ports:
      - "9090:9090"
    networks:
      dist-net:
        ipv4_address: 192.167.1.2

  server2:
    image: server
    ports:
      - "9091:9090"
    networks:
      dist-net:
        ipv4_address: 192.167.1.3

  server3:  
    image: server
    ports:
      - "9092:9090"
    networks:
      dist-net:
        ipv4_address: 192.167.1.4

  server4:  
    image: server
    ports:
      - "9093:9090"
    networks:
      dist-net:
        ipv4_address: 192.167.1.5

  server5:  
    image: server
    ports:
      - "9094:9090"
    networks:
      dist-net:
        ipv4_address: 192.167.1.6

  cliente:
    image: alg_genet
    networks:
      - dist-net
    depends_on: 
      - server1
      - server2
      - server3
      - server4
      - server5

networks:
  dist-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.1.0/12
          gateway: 192.167.1.1